[2024-08-05T13:22:22.578+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:22:22.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-08-20T15:00:00+00:00 [queued]>
[2024-08-05T13:22:22.715+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-08-20T15:00:00+00:00 [queued]>
[2024-08-05T13:22:22.716+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-05T13:22:22.773+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2022-08-20 15:00:00+00:00
[2024-08-05T13:22:22.789+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=759) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T13:22:22.804+0000] {standard_task_runner.py:64} INFO - Started process 842 to run task
[2024-08-05T13:22:22.797+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'scheduled__2022-08-20T15:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpfjluws3c']
[2024-08-05T13:22:22.814+0000] {standard_task_runner.py:91} INFO - Job 246: Subtask predict
[2024-08-05T13:22:23.110+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.predict scheduled__2022-08-20T15:00:00+00:00 [running]> on host db70dacab446
[2024-08-05T13:22:23.438+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2022-08-20T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-20T15:00:00+00:00'
[2024-08-05T13:22:23.440+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:22:23.494+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:22:23.497+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/predict.py", line 55, in predict
    with open(path+files) as f:
              ~~~~^~~~~~
TypeError: can only concatenate str (not "list") to str
[2024-08-05T13:22:23.536+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=predict, run_id=scheduled__2022-08-20T15:00:00+00:00, execution_date=20220820T150000, start_date=20240805T132222, end_date=20240805T132223
[2024-08-05T13:22:23.572+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 246 for task predict (can only concatenate str (not "list") to str; 842)
[2024-08-05T13:22:23.626+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T13:22:23.668+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:22:23.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
