[2024-08-05T13:20:45.750+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:20:45.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-08-07T15:00:00+00:00 [queued]>
[2024-08-05T13:20:45.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2022-08-07T15:00:00+00:00 [queued]>
[2024-08-05T13:20:45.976+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:20:46.043+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict> on 2022-08-07 15:00:00+00:00
[2024-08-05T13:20:46.081+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=577) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T13:20:46.085+0000] {standard_task_runner.py:64} INFO - Started process 704 to run task
[2024-08-05T13:20:46.094+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'scheduled__2022-08-07T15:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpvb6u1kdl']
[2024-08-05T13:20:46.104+0000] {standard_task_runner.py:91} INFO - Job 236: Subtask predict
[2024-08-05T13:20:46.440+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.predict scheduled__2022-08-07T15:00:00+00:00 [running]> on host db70dacab446
[2024-08-05T13:20:46.863+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2022-08-07T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-07T15:00:00+00:00'
[2024-08-05T13:20:46.882+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:20:46.976+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:20:46.990+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/predict.py", line 55, in predict
    with open(path+files) as f:
              ~~~~^~~~~~
TypeError: can only concatenate str (not "list") to str
[2024-08-05T13:20:47.045+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=predict, run_id=scheduled__2022-08-07T15:00:00+00:00, execution_date=20220807T150000, start_date=20240805T132045, end_date=20240805T132047
[2024-08-05T13:20:47.115+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 236 for task predict (can only concatenate str (not "list") to str; 704)
[2024-08-05T13:20:47.158+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-05T13:20:47.215+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:20:47.222+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
